### ISSUE TITLE
Repository 생성시 implements 된 항목 질문있습니다.

### ISSUE THREAD

**Issue by doublejkim** [djkeh/get-in-line#28]
안녕하세요. 강의 잘 듣고 있습니다. 

열심히 강의해주셨는데, 제가 놓친부분이 있는것인지 아니면 해당 내용이 누락이 되어 못찾는지 해결이 안되어 이렇게 질문 드립니다.

 Querydsl 부분 넘어가기전에 미리 작성해둔 코드로 추가해주신 부분이 있었는데 그중 Repository 에서 사용된 QEvent 항목을 어떻게 생성하는지 잘 모르겠습니다. 특정 부분에서 Generate 하게 하는 것 같은데 어떤 강의를 보면 되는것인지.. 아니면 어떻게 추가해주면되는지 가이드 부탁드리겠습니다.

해당 클래스가 추가된 커밋 링크는 아래와 같습니다.

감사합니다.

파일명 : EventRepository
질문 부분 : extends 한 QuerydslBinderCustomizer<QEvent>  부분 입니다

https://github.com/djkeh/get-in-line/commit/1cf473998a606a9778706be974b57e6c824772cc

**Comment by djkeh** [comment]
@doublejkim 님 반갑습니다.

해당 질문을 디스커션 #29 로 옮겨서 답변 드렸습니다. 확인해 보세요.
